Add controllers
den4ikos/java-shareit pull request #1
Opened 2022-12-10 16:32 UTC by den4ikos

2022-12-12 06:19 UTC, krylov-sergey-sergeevich requested changes
Привет, хорошо сделано, давай учтем комменты и добавим логгирование в контроллеры.

p.s Можно начинать читать про swagger чтобы к дипломной работе уметь с ним работать и сделать ее еще лучше

2022-12-12 06:19 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/Constants.java
> +    public static final String headerUserId = "X-Sharer-User-Id";
название static final переменных должно быть в таком формате HEADER_USER_ID

2022-12-12 06:19 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @DateTimeFormat
Обычно эту аннотацию используют чтобы паттерн задать, тут не требуется?

2022-12-12 06:19 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.getAllByUserId(userId);
Тут в дто не будем маппить?

2022-12-12 06:19 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.search(params);
Аналогичный вопрос про дто

2022-12-12 06:19 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/service/UserService.java
> +            throw new ValidationException("Email must be unique!");
Давай добавим сам емейл который проблемный в текст сообщения  об ошибке

2022-12-12 06:19 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    @DeleteMapping(value = "/{userId}")
Можно добавить еще аннотацию @NoContent

2022-12-12 17:19 UTC, den4ikos commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    @DeleteMapping(value = "/{userId}")
здесь не могу поставить nocontent, так как он возвращает статус 204, соответственно не пропускают тесты постмана

2022-12-12 17:19 UTC, den4ikos commented on src/main/java/ru/practicum/shareit/service/UserService.java
> +            throw new ValidationException("Email must be unique!");
готово

2022-12-12 17:19 UTC, den4ikos commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @DateTimeFormat
исправил

2022-12-12 17:20 UTC, den4ikos commented on src/main/java/ru/practicum/shareit/Constants.java
> +    public static final String headerUserId = "X-Sharer-User-Id";
исправил

2022-12-12 17:32 UTC, den4ikos commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.getAllByUserId(userId);
исправил

2022-12-12 17:32 UTC, den4ikos commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.search(params);
исправил

2022-12-13 14:10 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки, все хорошо - зачет!

2022-12-19 17:41 UTC, merged