Add bookings
den4ikos/java-shareit pull request #2
Opened 2022-12-31 08:40 UTC by den4ikos

2023-01-01 18:48 UTC, krylov-sergey-sergeevich requested changes
Привет

1) С новым годом)
2) Работа хорошая мало что можно улучшить, но кое что все же добавил, давай над этим поработаем

Буду ждать с исправлениями =)

2023-01-01 18:48 UTC, krylov-sergey-sergeevich commented on .gitignore
> +db/shareit.trace.db
Мне кажется следует всю папку db в pr

2023-01-01 18:48 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    email           varchar(255) not null unique
Уникальность и похожие штуки как primary key рекомендую создавать отдельно как CONSTRAINT ниже в объявление таблицы - но это не критично а скорее мое личное мнение из опыта

2023-01-01 18:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                .map(BookingMapper::bookingDtoToUser)
Рекомендую в мапперах всегда делать еще метод на N элементов тк такой маппинг части полезен плюс могут быть оптимизации в таких методах часто

2023-01-02 11:38 UTC, den4ikos commented on .gitignore
> +db/shareit.trace.db
пофиксил

2023-01-02 12:11 UTC, den4ikos commented on src/main/resources/schema.sql
> +    email           varchar(255) not null unique
исправил

2023-01-02 12:13 UTC, den4ikos commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                .map(BookingMapper::bookingDtoToUser)
хоршо, спасибо

2023-01-02 17:52 UTC, krylov-sergey-sergeevich approved these changes
Привет, все хорошо - зачет!

2023-01-02 17:52 UTC, krylov-sergey-sergeevich commented on .gitignore
> +db/*.db
Файлы из db все равно в pr остались, их надо удалить сделать коммит и после можно будет еще раз создать

2023-01-02 20:37 UTC, merged