Add item requests
den4ikos/java-shareit pull request #3
Opened 2023-01-08 14:06 UTC by den4ikos

2023-01-09 19:06 UTC, krylov-sergey-sergeevich requested changes
Привет :) В целом неплохой pr, но кое что улучшим

Бизнес код неплох, там по мелочам отписал, уже видно что навык наработан по тестам есть вопросик

1. Почитай про verify в Mockito полезная штука
2. В тестах очень часто вижу упущены модификаторы доступа для переменных и методов, надо как то единообразно систематизировать и еще что в некоторых тестах есть переменные которые используются в 2-3 и более тестах т.е. они определены на уровне класса и их используем, это прям опасно тк если когда нибудь тесты запараллелены будут это потом может аукнуться плюс так можно случайно поймать какой то side effect так называемый с другого теста

Буду ждать с доработками =)

2023-01-09 19:06 UTC, krylov-sergey-sergeevich commented on pom.xml
> -				<plugin>
Почему удалил?

2023-01-09 19:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/validation/CustomBookingValidation.java
> +        if (booking.getItem().getOwner() != null && booking.getItem().getOwner().getId().equals(user.getId())) {
Смотрю на строчку и думаю мжт сделать метод getItemOwnerId чтобы не дублировать каждый раз, но это так мысли вслух

2023-01-09 19:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                item.getRequestId() != null
Выглядит тяжко, давай вот эту и две следующих строки вынесем выше чтобы глаза не боялись

2023-01-09 19:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam Map<String, Object> params) {
Мне такой подход как то не очень нравится, там же у нас понятная логика что есть 2 параметра, а так нам напихать могут разного плюсы в коде появляется "фантомная" мапа которая содержит "то не знаю что", может просто сделаем 
@RequestParam(required = false) Integer from,
@RequestParam(required = false) Integer size

2023-01-10 17:35 UTC, den4ikos commented on src/main/java/ru/practicum/shareit/booking/validation/CustomBookingValidation.java
> +        if (booking.getItem().getOwner() != null && booking.getItem().getOwner().getId().equals(user.getId())) {
вынес в метод отдельный

2023-01-10 17:38 UTC, den4ikos commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                item.getRequestId() != null
fixed

2023-01-10 18:17 UTC, den4ikos commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam Map<String, Object> params) {
fixed

2023-01-10 18:24 UTC, den4ikos commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam Map<String, Object> params) {
Я думал принимать все параметры через Map, и запихнуть state в Map, так как я же все равно в сервисе эти все параметры приму, даже если будут какие то лишние, то они учитываться не будут. 
Не понимаю, почему этот способ плохой
Переделал в соответсвии с твоими замечаниями

2023-01-10 18:46 UTC, den4ikos commented on pom.xml
> -				<plugin>
Я не смог пофиксить ошибку на уровне гитхаб тестов 
Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.8:check

2023-01-11 06:18 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam Map<String, Object> params) {
Этот метод не то чтобы плох, лично я всегда в разработке люблю определенность поэтому и работаю на Java раз java дает нам возможность понимать тип объектов и их суть то я пользуюсь этим, а представь разработчик лезет в будущем в твой метод и видит мапу из которой ты достаешь параметры и такой, а что в ней еще может быть? Может это очень важная мапа и в ней еще пароли и т.д хранится

2023-01-11 06:32 UTC, krylov-sergey-sergeevich approved these changes
Привет

- Про мапу я немного другое имел ввиду, чтобы она совсем пропала из методов как параметр, но ладно на прием работы это не влияет
- Про тесты тоже немного другое имел ввиду, что мне не очень нравятся переменные которые определены в классе (обычно это dto) и используются разными тестами - но это тоже на зачет не влияет

Поэтому в целом работа неплохая - зачет!

2023-01-11 13:18 UTC, merged